



// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// // import { Navbar } from "@/components/layout/Navbar";
// import { ThemeProvider } from "@/providers/ThemeProvider";
// import { Toaster } from "@/components/ui/sonner";
// import { Navbar } from "@/components/layout/Navbar";
// import Footer from "@/components/layout/Footer";
// import HomePage from "@/components/layout/HomePage";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function CommonLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
    

//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="system"
//           enableSystem
//           disableTransitionOnChange
//         >
//           <Navbar></Navbar>
//           <HomePage></HomePage>
//           <Footer></Footer>
//           {children}
          
//           <Toaster richColors />
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }



































import Footer from '@/components/layout/Footer'
import { Navbar } from '@/components/layout/Navbar'
import React from 'react'

export default function CommonLayout({
    children,
}: {
    children: React.ReactNode
}) {
  return (
    <div>
       <Navbar></Navbar>
       {children}
        <Footer></Footer>
        
      
    </div>
  )
}


